generate_construct_overview <- function(dctSpec,
                                        headingLevel = 3) {

  res <-
    c("",
      paste0(ufs::repStr("#", headingLevel), " ", dctSpec$label),
      "",
      paste0(ufs::repStr("#", headingLevel+1), " ", dctSpec$label, " {#", dctSpec$id, "}"),
      "",
      format(Sys.time(), '*This overview was generated on %Y-%m-%d at %H:%M:%S %Z (GMT%z)*'),
      "",
      paste0("This Decentralized Construct Taxonomy specification was authored at ",
             ifelse(is.null(dctSpec$date),
                    "an unknown date (i.e. this was not specified in the DCT specification)",
                    dctSpec$date),
             "."),
      "",
      paste0("Unique Construct Identifier (UCID): ", dctSpec$id),
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Definition"),
      "",
      gsub("\\n", "\n\n", dctSpec$definition$definition) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing measurement instruments"),
      "",
      gsub("\\n", "\n\n", dctSpec$measure_dev$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding measurement instruments"),
      "",
      gsub("\\n", "\n\n", dctSpec$measure_code$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing manipulations"),
      "",
      gsub("\\n", "\n\n", dctSpec$manipulate_dev$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding manipulations"),
      "",
      gsub("\\n", "\n\n", dctSpec$manipulate_code$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing aspects"),
      "",
      gsub("\\n", "\n\n", dctSpec$aspect_dev$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding aspects"),
      "",
      paste0("*When coding aspects, use the following code: **`dct:", dctSpec$id, "`***"),
      "",
      gsub("\\n", "\n\n", dctSpec$aspect_code$instruction) %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Relationships with other constructs"),
      "",
      ifelse(is.null(dctSpec$rel),
             "*Not specified*",
             ifelse(all(c("id", "type") %in% names(dctSpec$rel)),
                    paste0("- Related to dct:", dctSpec$rel$id, " with relationship of type ",
                           dctSpec$rel$type, "\n"),
                    paste0(unlist(lapply(dctSpec$rel, function(i) {
                      return(paste0("- Related to dct:", i$id, " with relationship of type ",
                                    i$type, "\n"));
                    })), collapse="\n"))),
#      paste0(as.character(dctSpec$rel), collapse="--> ", sep=" ") %||% "*Not specified*",
      "");

  return(res);
}
