generate_construct_overview <- function(dctSpec,
                                        headingLevel = 3) {

  res <-
    c("",
      paste0(ufs::repStr("#", headingLevel), " ", dctSpec$label),
      "",
      format(Sys.time(), '*This overview was generated on %Y-%m-%d at %H:%M:%S %Z (GMT%z)*'),
      "",
      paste0("This Decentralized Construct Taxonomy specification was authored at ", dctSpec$date %||% "an unknown date", "."),
      "",
      paste0("Identifier: ", dctSpec$id),
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Definition"),
      "",
      dctSpec$definition$definition %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing measurement instruments"),
      "",
      dctSpec$measure_dev$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding measurement instruments"),
      "",
      dctSpec$measure_code$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing manipulations"),
      "",
      dctSpec$manipulate_dev$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding manipulations"),
      "",
      dctSpec$manipulate_code$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for developing aspects"),
      "",
      dctSpec$aspect_dev$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Instruction for coding aspects"),
      "",
      paste0("*When coding aspects, use the following code: **`dct:", dctSpec$id, "`***"),
      "",
      dctSpec$aspect_code$instruction %||% "*Not specified*",
      "",
      paste0(ufs::repStr("#", headingLevel+1), " Relationships with other constructs"),
      "",
      paste0(as.character(dctSpec$rel), collapse="--> ", sep=" ") %||% "*Not specified*",
      "");

  return(res);
}
